name: Scheduled Paper Collector

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"   # 0h s√°ng VN (17h UTC h√¥m tr∆∞·ªõc)
    - cron: "0 5 * * *"    # 12h tr∆∞a VN (5h UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup Google credentials
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > sa_key.json
          echo "‚úÖ Created sa_key.json"
        shell: bash

      - name: Debug credentials file
        run: |
          echo "üîç Checking credential file content..."
          echo "----------------------------------------"
          cat sa_key.json || echo "‚ùå File not found!"
          echo "----------------------------------------"
        
      - name: Run main script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: sa_key.json
        run: |
          python run.py

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add results/ database/
          git commit -m "new paper $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          git fetch origin main
          git pull --rebase origin main
          
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
